[package]
name = "neovide"
version = "0.4.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"
build = "build.rs"
description = "A simple GUI for Neovim."

[dependencies]
euclid = "0.20.7"
font-kit = { git = "https://github.com/servo/font-kit", rev = "751ab77" }
skribo = { git = "https://github.com/svermeulen/skribo", branch = "MacOsFix" }
lru = "0.4.3"
skulpin = { git = "https://github.com/kethku/skulpin", branch = "winit_20" }
derive-new = "0.5"
rmpv = "0.4.4"
rust-embed = { version = "5.2.0", features = ["debug-embed"] }
image = "0.22.3"
nvim-rs = { git = "https://github.com/kethku/nvim-rs", features = [ "use_tokio" ] }
tokio = { version = "0.2.9", features = [ "blocking", "process", "time" ] }
async-trait = "0.1.18"
lazy_static = "1.4.0"
unicode-segmentation = "1.6.0"
log = "0.4.8"
flexi_logger = { version = "0.14.6", default-features = false }
anyhow = "1.0.26"
crossbeam = "0.7"
parking_lot="0.10.0"

[build-dependencies]
winres = "0.1.11"

[profile.release]
debug = true

[package.metadata.bundle]
name = "Neovide"
identifier = "com.kethku.neovide"
icon = ["assets/nvim.ico"]
version = "0.4.0"
resources = []
copyright = "Copyright (c) keith 2020. All rights reserved."
category = "Productivity"
short_description = "A simple GUI for Neovim."
long_description = """
This is a simple graphical user interface for Neovim. Where possible there are some graphical improvements, but it should act functionally like the terminal UI.
"""
